-- CreateTable
CREATE TABLE "PRODUCTTAG" (
    "productId" INTEGER NOT NULL,
    "addAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tagId" INTEGER NOT NULL,

    CONSTRAINT "PRODUCTTAG_pkey" PRIMARY KEY ("productId","tagId")
);

-- CreateTable
CREATE TABLE "TAG" (
    "id" SERIAL NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TAG_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "PRODUCTTAG" ADD CONSTRAINT "PRODUCTTAG_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PRODUCTTAG" ADD CONSTRAINT "PRODUCTTAG_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "TAG"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
